services:
  backend:
    container_name: "alchemy_prompt_backend"
    build:
      dockerfile: "./backend_dockerfile/backend.Dockerfile"
    tty: true
    working_dir: "/var/www/html"
    volumes:
      - ./backend_env:/var/www/html
  frontend:
    container_name: "alchemy_prompt_frontend"
    build:
      dockerfile: "./frontend_dockerfile/frontend.Dockerfile"
    tty: true
    working_dir: "/var/www/html"
    volumes:
      - ./frontend_env:/var/www/html
  db:
    container_name: "alchemy_prompt_db"
    image: mysql:8.0.43-bookworm
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.env_mysql
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
