services:
  backend:
    container_name: "alchemy_prompt_backend"
    build:
      dockerfile: "./backend_dockerfile/backend.Dockerfile"
    tty: true
    working_dir: "/var/www/html"
    volumes:
      - alchemy_prompt_backend:/var/www/html
  frontend:
    container_name: "alchemy_prompt_frontend"
    build:
      dockerfile: "./frontend_dockerfile/frontend.Dockerfile"
    tty: true
    working_dir: "/var/www/html"
    volumes:
      - alchemy_prompt_frontend:/var/www/html
volumes:
  alchemy_prompt_backend:
  alchemy_prompt_frontend:
