services:
  backend:
    container_name: "alchemy_prompt_backend"
    image: python:3.13-slim-bookworm
    tty: true
    working_dir: "/var/www/html"
    volumes:
      - ./backend_env:/var/www/html
  frontend:
    container_name: "alchemy_prompt_frontend"
    image: node:25.0.0-bookworm-slim
    tty: true
    working_dir: "/var/www/html"
    ports:
      - 8080:3000
    volumes:
      - ./frontend_env:/var/www/html
  db:
    container_name: "alchemy_prompt_db"
    image: mysql:8.0.43-bookworm
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.env_mysql
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
