services:
  backend:
    container_name: "alchemy_prompt_backend"
    build:
      dockerfile: ./backend_infra/backend.Dockerfile
    tty: true
    working_dir: "/var/www/html/app"
    ports:
      - 8081:8000
    volumes:
      - ./backend_env:/var/www/html
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    container_name: "alchemy_prompt_frontend"
    image: node:25.0.0-bookworm-slim
    tty: true
    working_dir: "/var/www/html/alchemy-prompt"
    ports:
      - 8080:3000
    volumes:
      - ./frontend_env:/var/www/html
    command: npm run dev
